import numpy as np
zeros_array = np.zeros((3, 4))
print(f"NumPy array of zeros:\n{zeros_array}")
ones_array = np.ones((3, 4))
print(f"NumPy array of ones:\n{ones_array}")
full_array = np.full((3, 4), 7)
print(f"NumPy array filled with 7s:\n{full_array}")
identity_array = np.eye(3)
print(f"NumPy identity matrix:\n{identity_array}")
empty_array = np.empty((3, 4))
print(f"NumPy empty array:\n{empty_array}")
range_array = np.arange(0, 12, 2)
print(f"NumPy array with a range of values:\n{range_array}")
linspace_array = np.linspace(0, 1, 5)
print(f"NumPy array with linearly spaced values:\n{linspace_array}")
random_array = np.random.random((3, 4))
print(f"NumPy array with random values:\n{random_array}")